---
name: Egg-Plugin-Net-Ping
version: 3.00
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: Net::Ping for Egg plugin.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Egg::Release: 2
  Net::Ping: 2.31
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Egg::Plugin::Net::Ping:
    file: lib/Egg/Plugin/Net/Ping.pm
    version: 3.00
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
